### ISSUE TITLE
接受信息有问题

### ISSUE THREAD

**Issue by ggboypro** [lz1998/Spring-CQ#7]
CQHTTP日志显示发送成功.Spring-CQ最多只输出2位的字符、字母及数字,中文不行.但最初的测试,可发送其他中文文字信息.
环境是mac + 虚拟机Win10.Spring-CQ在mac上,酷Q及CQHttp在虚拟机上.排查了代码,没啥问题

**Comment by ggboypro** [comment]
源程序,down下来没改动

**Comment by lz1998** [comment]
检查酷Q日志，右键悬浮窗，点击日志，看有没有发送，如果发送了说明是被腾讯屏蔽
输出是什么问题
能附上截图吗

**Comment by lz1998** [comment]
或者可以加一下群335783090

**Comment by ggboypro** [comment]
今天重新打开,可以发送好了
