### ISSUE TITLE
有没有查询群或者添加群的功能？

### ISSUE THREAD

**Issue by liufitch** [lz1998/Spring-CQ#8]
有没有查询群或者添加群的功能？

**Comment by lz1998** [comment]
cq.getGroupInfo().getData() 获取群信息
cq.getGroupList().getData() 获取群列表

加群功能没有

**Comment by liufitch** [comment]
> cq.getGroupInfo().getData() 获取群信息
> cq.getGroupList().getData() 获取群列表
> 
> 加群功能没有

获取群列表是根据关键字搜索群吗？

**Comment by lz1998** [comment]
获取群列表就是获取机器人自己加了哪些群
