### ISSUE TITLE
linux服务器部署coolQ和插件后并不能ws到spring中，但windows可以。

### ISSUE THREAD

**Issue by ChunChunWeb** [lz1998/Spring-CQ#9]
使用了richardchien/cqhttp 和coolq/wine-coolq +配置文件（应该是一样的）测试结果都不行，日志显示
![image](https://user-images.githubusercontent.com/32215562/85007940-ceba2700-b18e-11ea-8777-1c9c35fcdf24.png)
加载的配置信息：
![image](https://user-images.githubusercontent.com/32215562/85007984-ded20680-b18e-11ea-96b1-10b15a50e96e.png)
确认服务器能ws访问：
![image](https://user-images.githubusercontent.com/32215562/85008020-edb8b900-b18e-11ea-8e22-d166e8af44c6.png)

望博主查看下，windows测试完美，能实现我通过coolQ控制我页面，发表文章等功能，十分感谢，所以想部署到linux下，但经测试，websocket连接不上。

**Comment by ChunChunWeb** [comment]
windows启动的coolQ能访问服务器搭建spring功能。

**Comment by ChunChunWeb** [comment]
![image](https://user-images.githubusercontent.com/32215562/85010019-eb0b9300-b191-11ea-9c24-a4931c928f9b.png)
对了，在linux中，这里不会打印日志，跟windows的区别。

**Comment by lz1998** [comment]
> 使用了richardchien/cqhttp 和coolq/wine-coolq +配置文件（应该是一样的）测试结果都不行，日志显示
> ![image](https://user-images.githubusercontent.com/32215562/85007940-ceba2700-b18e-11ea-8777-1c9c35fcdf24.png)
> 加载的配置信息：
> ![image](https://user-images.githubusercontent.com/32215562/85007984-ded20680-b18e-11ea-96b1-10b15a50e96e.png)
> 确认服务器能ws访问：
> ![image](https://user-images.githubusercontent.com/32215562/85008020-edb8b900-b18e-11ea-8e22-d166e8af44c6.png)
> 
> 望博主查看下，windows测试完美，能实现我通过coolQ控制我页面，发表文章等功能，十分感谢，所以想部署到linux下，但经测试，websocket连接不上。

这是因为之前README里面的docker指令写错了，`CQHTTP_WS_REVERSE_USE_UNIVERSAL_CLIENT`写成了`CQHTTP_WS_REVERSE_UNIVERSAL_CLIENT`，漏了`USE`，使用最新版README里面的指令即可

```bash
docker run -d --name cq01 \
-v $(pwd)/coolq:/home/user/coolq \
--net=host \
-e VNC_PASSWD=你的VNC密码(不超过8位) \
-e COOLQ_URL=http://dlsec.cqp.me/cqa-tuling \
-e COOLQ_ACCOUNT=你的机器人QQ号 \
-e CQHTTP_USE_HTTP=false \
-e CQHTTP_USE_WS_REVERSE=true \
-e CQHTTP_WS_REVERSE_URL=ws://127.0.0.1:8081/ws/cq/ \
-e CQHTTP_WS_REVERSE_USE_UNIVERSAL_CLIENT=true \
-e CQHTTP_ENABLE_HEARTBEAT=true \
-e CQHTTP_HEARTBEAT_INTERVAL=60000 \
richardchien/cqhttp
```

**Comment by ChunChunWeb** [comment]
使用新配置以后，已解决
